// ---------------------------------------------------------------------------
// Grille tarifaire par défaut — miroir exact de supabase/migrations/0003.
// Sert à la fois au mode démo et de référence pour réinitialiser la grille.
// ---------------------------------------------------------------------------

import type { OffrePromo, Parametre, PricingRule } from '@/lib/types';

export const PRICING_RULES_DEFAUT: Omit<PricingRule, 'id'>[] = [
  {
    code: 'base_site_essentiel',
    nom: 'Base « Site Essentiel » (paiement unique)',
    type: 'base',
    prix: 249,
    unite: 'forfait',
    quantifiable: false,
    description:
      'Génération IA complète, jusqu’à 5 pages, design sur-mesure par secteur, responsive, formulaire de contact, SEO de base, déploiement test + production automatisé',
    cout_ia_estime: 4.5,
    cout_hebergement_mensuel: 0,
    actif: true,
    ordre: 1,
  },
  {
    code: 'abo_hebergement',
    nom: 'Abonnement Hébergement & Maintenance',
    type: 'abonnement',
    prix: 19,
    unite: 'mois',
    quantifiable: false,
    description:
      'Hébergement (Vercel/Cloudflare), certificat SSL, sauvegardes, monitoring, 2 mises à jour de contenu incluses par an',
    cout_ia_estime: 0,
    cout_hebergement_mensuel: 0.45,
    actif: true,
    ordre: 2,
  },
  {
    code: 'page_supplementaire',
    nom: 'Page supplémentaire',
    type: 'option',
    prix: 29,
    unite: 'page',
    quantifiable: true,
    description: 'Page additionnelle générée et intégrée par l’IA',
    cout_ia_estime: 0.8,
    cout_hebergement_mensuel: 0.02,
    actif: true,
    ordre: 3,
  },
  {
    code: 'module_reservation',
    nom: 'Système de réservation / rendez-vous en ligne',
    type: 'option',
    prix: 89,
    unite: 'forfait',
    quantifiable: false,
    description: 'Module de prise de RDV intégré au site',
    cout_ia_estime: 1.2,
    cout_hebergement_mensuel: 0.05,
    actif: true,
    ordre: 4,
  },
  {
    code: 'boutique_stripe',
    nom: 'Boutique en ligne (paiement Stripe)',
    type: 'option',
    prix: 199,
    unite: 'forfait',
    quantifiable: false,
    description: 'Catalogue produits + paiement en ligne',
    cout_ia_estime: 2.5,
    cout_hebergement_mensuel: 0.1,
    actif: true,
    ordre: 5,
  },
  {
    code: 'multilingue',
    nom: 'Multilingue',
    type: 'option',
    prix: 39,
    unite: 'langue',
    quantifiable: true,
    description: 'Traduction IA + adaptation SEO par langue',
    cout_ia_estime: 0.6,
    cout_hebergement_mensuel: 0.02,
    actif: true,
    ordre: 6,
  },
  {
    code: 'refonte_premium',
    nom: 'Refonte design premium (animations, sur-mesure poussé)',
    type: 'option',
    prix: 99,
    unite: 'forfait',
    quantifiable: false,
    description: 'Templates avancés, direction artistique renforcée',
    cout_ia_estime: 1.5,
    cout_hebergement_mensuel: 0,
    actif: true,
    ordre: 7,
  },
  {
    code: 'redaction_photo_ia',
    nom: 'Rédaction et retouche photo IA',
    type: 'option',
    prix: 49,
    unite: 'forfait',
    quantifiable: false,
    description: 'Optimisation visuelle du contenu fourni par le client',
    cout_ia_estime: 0.9,
    cout_hebergement_mensuel: 0,
    actif: true,
    ordre: 8,
  },
  {
    code: 'livraison_express',
    nom: 'Livraison express (48h)',
    type: 'option',
    prix: 79,
    unite: 'forfait',
    quantifiable: false,
    description: 'Priorité de génération et de validation',
    cout_ia_estime: 0.3,
    cout_hebergement_mensuel: 0,
    actif: true,
    ordre: 9,
  },
  {
    code: 'maj_ponctuelle',
    nom: 'Mise à jour ponctuelle hors abonnement',
    type: 'option',
    prix: 25,
    unite: 'forfait',
    quantifiable: true,
    description: 'Modification à la demande, hors forfait maintenance',
    cout_ia_estime: 0.25,
    cout_hebergement_mensuel: 0,
    actif: true,
    ordre: 10,
  },
  {
    code: 'pack_visibilite',
    nom: 'Pack visibilité (fiche Google Business + réseaux sociaux)',
    type: 'option',
    prix: 59,
    unite: 'forfait',
    quantifiable: false,
    description: 'Configuration des profils publics liés au site',
    cout_ia_estime: 0.2,
    cout_hebergement_mensuel: 0,
    actif: true,
    ordre: 11,
  },
];

export const OFFRES_PROMO_DEFAUT: Omit<OffrePromo, 'id'>[] = [
  {
    code: 'LANCEMENT30',
    libelle: '-30 % sur les 3 premiers mois d’abonnement',
    type_remise: 'pourcentage_abonnement',
    valeur: 30,
    duree_mois: 3,
    actif: true,
    date_debut: null,
    date_fin: null,
  },
  {
    code: 'PREMIERMOIS',
    libelle: '1er mois d’hébergement offert',
    type_remise: 'mois_offerts',
    valeur: 1,
    duree_mois: 1,
    actif: true,
    date_debut: null,
    date_fin: null,
  },
  {
    code: 'OUVERTURE20',
    libelle: '-20 % sur la prestation initiale',
    type_remise: 'pourcentage_oneshot',
    valeur: 20,
    duree_mois: 0,
    actif: false,
    date_debut: null,
    date_fin: null,
  },
];

export const PARAMETRES_DEFAUT: Parametre[] = [
  {
    cle: 'marge_min_oneshot_pct',
    valeur: '70',
    description: 'Alerte si la marge sur la prestation initiale passe sous ce pourcentage',
  },
  {
    cle: 'marge_min_abonnement_eur',
    valeur: '12',
    description: 'Alerte si la marge nette mensuelle de l’abonnement passe sous ce montant (€)',
  },
  {
    cle: 'cout_ia_par_page_eur',
    valeur: '0.80',
    description: 'Coût moyen d’un appel de génération IA par page',
  },
  {
    cle: 'cout_hebergement_mensuel_eur',
    valeur: '0.45',
    description: 'Coût réel mensuel d’hébergement mutualisé par site',
  },
  {
    cle: 'delai_suspension_impaye_jours',
    valeur: '15',
    description: 'Délai avant suspension du site après échec de paiement',
  },
  {
    cle: 'validite_devis_jours',
    valeur: '30',
    description: 'Durée de validité d’un devis',
  },
  {
    cle: 'retention_prospect_mois',
    valeur: '36',
    description: 'RGPD : conservation limitée à 3 ans après le dernier contact actif',
  },
];
